//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKLicense.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver_details
    {
        public System.Guid id_driver { get; set; }
        public string physical_id { get; set; }
        public string driver_first_name { get; set; }
        public string driver_middle_name { get; set; }
        public string driver_last_name { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string nationalty { get; set; }
        public string phone_number { get; set; }
        public string back_code { get; set; }
        public string permanent_contact_address { get; set; }
        public string next_of_kin { get; set; }
        public string next_of_kin_mobile { get; set; }
        public string passport_path { get; set; }
        public Nullable<System.DateTime> date_registered { get; set; }
        public Nullable<System.Guid> DataCapturedBy { get; set; }
        public Nullable<System.DateTime> expire_date { get; set; }
        public string driveable_description { get; set; }
        public Nullable<bool> imagetype_identifier { get; set; }
        public Nullable<System.DateTime> AM_10 { get; set; }
        public Nullable<System.DateTime> AM_11 { get; set; }
        public string AM_12 { get; set; }
        public Nullable<System.DateTime> A1_10 { get; set; }
        public Nullable<System.DateTime> A1_11 { get; set; }
        public string A1_12 { get; set; }
        public Nullable<System.DateTime> A2_10 { get; set; }
        public Nullable<System.DateTime> A2_11 { get; set; }
        public string A2_12 { get; set; }
        public Nullable<System.DateTime> A_10 { get; set; }
        public Nullable<System.DateTime> A_11 { get; set; }
        public string A_12 { get; set; }
        public Nullable<System.DateTime> B1_10 { get; set; }
        public Nullable<System.DateTime> B1_11 { get; set; }
        public string B1_12 { get; set; }
        public Nullable<System.DateTime> B_10 { get; set; }
        public Nullable<System.DateTime> B_11 { get; set; }
        public string B_12 { get; set; }
        public Nullable<System.DateTime> C1_10 { get; set; }
        public Nullable<System.DateTime> C1_11 { get; set; }
        public string C1_12 { get; set; }
        public Nullable<System.DateTime> C_10 { get; set; }
        public Nullable<System.DateTime> C_11 { get; set; }
        public string C_12 { get; set; }
        public Nullable<System.DateTime> D1_10 { get; set; }
        public Nullable<System.DateTime> D1_11 { get; set; }
        public string D1_12 { get; set; }
        public Nullable<System.DateTime> D_10 { get; set; }
        public Nullable<System.DateTime> D_11 { get; set; }
        public string D_12 { get; set; }
        public Nullable<System.DateTime> BE_10 { get; set; }
        public Nullable<System.DateTime> BE_11 { get; set; }
        public string BE_12 { get; set; }
        public Nullable<System.DateTime> C1E_10 { get; set; }
        public Nullable<System.DateTime> C1E_11 { get; set; }
        public string C1E_12 { get; set; }
        public Nullable<System.DateTime> CE_10 { get; set; }
        public Nullable<System.DateTime> CE_11 { get; set; }
        public string CE_12 { get; set; }
        public Nullable<System.DateTime> D1E_10 { get; set; }
        public Nullable<System.DateTime> D1E_11 { get; set; }
        public string D1E_12 { get; set; }
        public Nullable<System.DateTime> DE_10 { get; set; }
        public Nullable<System.DateTime> DE_11 { get; set; }
        public string DE_12 { get; set; }
        public Nullable<System.DateTime> FKQ_10 { get; set; }
        public Nullable<System.DateTime> FKQ_11 { get; set; }
        public string FKQ_12 { get; set; }
        public string card_id { get; set; }
        public string Title { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
